# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmJkZWY5ZWE4YTBhNmE5NGZkNDE2OWY2MzUzZDVmYzYxYWRlYzMyZGE4MzM2MTg4MjBjYzQxNWJmZGZiODk3MWFmYzJkN2ViYmM1ZWViZDMyMDQ0OTMyOGRjYThkMWExMDU2MzJlOWZhMmY0MmUwNDk1Y2RlODE1YzhlMzdmZTA=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
